### PR TITLE
Add relation from Sample to Parameter.

### PR DESCRIPTION
**Pull request by RKrahl**
As discussed in last week's meeting, we also have sample parameters. In order to be able to search for samples by their parameter values it would be needed to have a relation from Sample to Parameter.

### CODE REVIEW

**Comment by garethcmurphy** [comment]
I can't find a decision concerning this in the meeting minutes. As far as I am aware, the scope was to be limited to Dataset.parameters and Sample.parameters/full sample database functionality is currently out of scope for PaNOSC/ExPaNDS

**Comment by RKrahl** [comment]
According to the meeting minutes, there was a discussion on sample parameters, but no conclusion.  So this is still open and we need a decision on this.  It has furthermore been decided in the meeting that amendments to the API specification should be made in the form of GitHub issues and pull request in this repository.  The present pull request follows the agreed procedure to request that pending decision.

Regarding the scope, the search API is not a database at all.  The API is supposed to provide access to the metadata stored in the local catalogues via a common search portal.  We have some experiments where detailed informations on the sample is crucial to make any use of the data.  This includes the full history of how that particular sample has been processed.  So it is important to distinguish individual samples and the user would need to be able to search for individual samples first.  Not allowing sample parameter would therefore exclude relevant parts of the metadata that we have from being searchable and accessible in the common portal.  I don't believe this is in line with the goal of PaNOSC and ExPaNDS to provide FAIR data.

**Comment by garethcmurphy** [comment]
Hi Rolf, 

The subset of sample metadata which is relevant to a Dataset can be queried via Dataset.parameters. This may cover your use case without the need for a full scale Sample.parameters

**Comment by RKrahl** [comment]
No, it does not cover this use case. As I wrote:

> So it is important to distinguish individual samples and the user would need to be able to search for individual samples first.

Obviously the search for the individual sample would need to be based on some properties of the sample. It is also obvious that such a search is impossible if the API does not expose any properties of that sample.

**Comment by andygotz** [comment]
We discussed this at the ICAT F2F and unanimously agreed we need sample parameters. We (HZB, DLS, STFC, ESRF, ALBA) strongly support adding these. It would be great if you could accept our request. What problems could adding sample parameters cause eventually?

**Comment by zjttoefs** [comment]
You can use parameters in the query for datasets and documents, that is why it looks like only those can carry parameters in the data model. 
It is down to the local mapping in the concrete implementation to make the correct association. When looking for `sample_temperature` that could be in the sample table in one backend storage, in a table for a device (the sample environment) somewhere else or on the dataset as part of the measurement. 
In the ontology task we would like to focus on the dictionary of parameter names. The mapping to the local data model is trivial. Agreeing on where which parameter needs to be placed in the model does not effect the search quality, as long as we can keep the names unique.

**Pull request closed without merging**
